version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "All"
    ports:
      - 2113:2113
      - 1113:1113

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass4Dev1!"
      ACCEPT_EULA: "Y"
    ports:
      - 1435:1433
